default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wip_development

test:
  <<: *default
  database: wip_test

production:
  <<: *default
  database: wip_production
  username: wip
  password: <%= ENV["WIP_DATABASE_PASSWORD"] %>

trampconosco:
  <<: *default
  database: trampconosco_db
  username: trampenterprise
  password: tramphauntmex3
  host: localhost
  port: 5432
